=== uo277306/SEW-EscritorioVirtual/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ruta" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ruta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="agencia" />
                <xs:element ref="descripcion" />
                <xs:element ref="personas-adecuadas" />
                <xs:element ref="referencias" />
                <xs:element ref="hitos" />
                <xs:element ref="recomendacion" />
                <xs:element ref="coordenadas" />
            </xs:sequence>
            <xs:attribute name="nombre" use="required" />
            <xs:attribute name="tipo" use="required" />
            <xs:attribute name="medio-transporte" use="required" />
            <xs:attribute name="fecha-inicio" type="xs:date" use="optional" />
            <xs:attribute name="hora-inicio" type="xs:time" use="optional" />
            <xs:attribute name="duracion" use="required" type="xs:duration" />
            <xs:attribute name="lugar-inicio" use="required" />
            <xs:attribute name="direccion-inicio" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="agencia" type="xs:string" />
    <xs:element name="descripcion" type="xs:string" />
    <xs:element name="personas-adecuadas" type="xs:string" />
    <xs:element name="recomendacion">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0" />
                <xs:maxInclusive value="10" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="referencia" type="xs:string" />
    <xs:element name="hitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="hito">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="galeria-fotos" />
                <xs:element ref="galeria-videos" />
                <xs:element ref="coordenadas" />
            </xs:sequence>
            <xs:attribute name="nombre" use="required" />
            <xs:attribute name="distancia-hito-anterior" use="required" />
        </xs:complexType>
    </xs:element>
    <xs:element name="galeria-fotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="5" ref="foto" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="galeria-videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="3" ref="video" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="foto" type="xs:string" />
    <xs:element name="video" type="xs:string" />
    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:attribute name="longitud" use="required" />
            <xs:attribute name="latitud" use="required" />
            <xs:attribute name="altitud" use="required" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== uo277306/SEW-EscritorioVirtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rutas.xsd">
    <ruta nombre="Cusco" tipo="Arquitectura y monumentos" medio-transporte="andando"
        duracion="P3D"
        lugar-inicio="Mercado Central de San Pedro"
        direccion-inicio="Thupaq Amaru 477, Cusco 08002, Perú"
    >
        <agencia>Sin agencia</agencia>
        <descripcion>Visitar hoy esta ciudad colonial declarada Patrimonio de la Humanidad es
            caminar por un legado tangible de un imperio fascinante.</descripcion>
        <personas-adecuadas>1-5</personas-adecuadas>
        <referencias>
            <referencia>https://www.viajeroscallejeros.com/lugares-que-visitar-en-cusco/</referencia>
            <referencia>https://www.viajandoporelmundomundial.com/que-ver-en-cuzco/</referencia>
            <referencia>
                https://www.tripadvisor.es/Attractions-g294314-Activities-Cusco_Cusco_Region.html</referencia>
        </referencias>
        <hitos>
            <hito nombre="Plaza de Armas" distancia-hito-anterior="600">
                <galeria-fotos>
                    <foto>plaza-de-armas.jpeg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-13.516573771916507" longitud="-71.97873383105876"
                    altitud="3403.16" />
            </hito>
            <hito nombre="Muyuq Marka" distancia-hito-anterior="1600">
                <galeria-fotos>
                    <foto>muyuq-maya.peg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-13.509062864301848" longitud="-71.98276787613783"
                    altitud="3580.91" />
            </hito>
            <hito nombre="Qorikancha" distancia-hito-anterior="2000">
                <galeria-fotos>
                    <foto>qorikancha.jpeg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-13.520069582584924" longitud="-71.97522315999254"
                    altitud="3387.8" />
            </hito>
        </hitos>
        <recomendacion>8</recomendacion>
        <coordenadas latitud="-13.520850734845185" longitud="-71.98268201385343" altitud="3410.37" />
    </ruta>
    <ruta nombre="Machu Picchu" tipo="Paisajística" medio-transporte="andando"
        duracion="PT2H"
        lugar-inicio="Sanctuary Lodge, A Belmond Hotel, Machu Picchu"
        direccion-inicio="Carretera Hiram Bingham Km 7.5, Aguas Calientes 08680, Perú"
    >
        <agencia>boletomachupicchu</agencia>
        <descripcion>Este yacimiento arqueológico es uno de los más misteriosos e indescifrables de
            la América Precolombina. Hay muchas preguntas sobre Machu Picchu y pocas respuestas, y
            quizá por ello atrae tanto.</descripcion>
        <personas-adecuadas>1-5</personas-adecuadas>
        <referencias>
            <referencia>https://www.boletomachupicchu.com/circuitos-recorrer-machu-picchu/</referencia>
            <referencia>https://www.viviendodeviaje.com/machu-picchu/</referencia>
            <referencia>https://www.machupicchu.gob.pe/circuitos-establecidos/</referencia>
        </referencias>
        <hitos>
            <hito nombre="Templo del Sol" distancia-hito-anterior="300">
                <galeria-fotos>
                    <foto>templo-del-sol.jpeg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-13.163980558076373" longitud="-72.54473116383839"
                    altitud="2439.82" />
            </hito>
            <hito nombre="Plaza Sagrada" distancia-hito-anterior="400">
                <galeria-fotos>
                    <foto>plaza-sagrada.peg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-13.163531345883609" longitud="-72.54531052971046"
                    altitud="2464.3" />
            </hito>
            <hito nombre="Intihuatana" distancia-hito-anterior="250">
                <galeria-fotos>
                    <foto>intihuatana.jpeg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-13.163039224674163" longitud="-72.54556727966666"
                    altitud="2466.49" />
            </hito>
        </hitos>
        <recomendacion>6</recomendacion>
        <coordenadas latitud="-13.165913249739114" longitud="-72.54300386229382" altitud="2433.07" />
    </ruta>
    <ruta nombre="Islas del Titicaca" tipo="Paisajística" medio-transporte="lancha"
        duracion="P1D"
        lugar-inicio="Puno"
        direccion-inicio="5X7P+X65, Unnamed Road, Puno 21001, Perú"
    >
        <agencia>boletomachupicchu</agencia>
        <descripcion>El Lago Titicaca, cuenta con islas que mantienen vigente sus tradiciones pre
            colombinas. Existen tres importantes islas que son las más preguntadas por los viajeros
            que no le tienen miedo a las alturas.</descripcion>
        <personas-adecuadas>1-3</personas-adecuadas>
        <referencias>
            <referencia>https://www.perurail.com/es/blog/conoce-mas-sobre-las-tres-islas-mas-importantes-del-lago-titicaca/</referencia>
            <referencia>https://es.wikipedia.org/wiki/Islas_flotantes_de_los_uros</referencia>
            <referencia>https://www.elconfidencial.com/viajes/2021-04-28/las-sorprendentes-islas-flotantes-del-lago-titicaca_3051255/</referencia>
        </referencias>
        <hitos>
            <hito nombre="Isla flotante de los Uros" distancia-hito-anterior="13000">
                <galeria-fotos>
                    <foto>isla-uros.jpeg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-15.732675696538209" longitud="-69.89603700471716"
                    altitud="3816.97" />
            </hito>
            <hito nombre="Isla Taquile" distancia-hito-anterior="7500">
                <galeria-fotos>
                    <foto>taquile.peg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-15.770604349740433" longitud="-69.68624085159898"
                    altitud="3943.05" />
            </hito>
            <hito nombre="Isla Amantaní" distancia-hito-anterior="4000">
                <galeria-fotos>
                    <foto>isla-amantani.jpeg</foto>
                </galeria-fotos>
                <galeria-videos>
                </galeria-videos>
                <coordenadas latitud="-15.66427002195403" longitud="-69.71836657535265"
                    altitud="4102.39" />
            </hito>
        </hitos>
        <recomendacion>10</recomendacion>
        <coordenadas latitud="-15.835032296645837" longitud="-70.01444964546768" altitud="3819.06" />
    </ruta>
</rutas>
